### ISSUE TITLE
`EnrollmentContext` config object: exception on RA component if set to `true`

### ISSUE THREAD

**Issue by DDvO** [siemens/LightweightCmpRa#24]
I get
```
[main] WARN com.siemens.pki.cmpracomponent.msgvalidation.BaseCmpException - error at ClientUpstream: message is incomplete protected but protection is required
Exception in thread "main" java.lang.RuntimeException: error processing invokeEnrollment
	at com.siemens.pki.cmpclientcomponent.main.CmpClient.invokeEnrollment(CmpClient.java:575)
	at com.siemens.pki.lightweightcmpclient.main.CliCmpClient.doEnrollment(CliCmpClient.java:206)
	at com.siemens.pki.lightweightcmpclient.main.CliCmpClient.runClient(CliCmpClient.java:377)
	at com.siemens.pki.lightweightcmpclient.main.CliCmpClient.main(CliCmpClient.java:317)
Caused by: CmpException [failInfo=65536, errorDetails=ClientUpstream: message is incomplete protected but protection is required]
	at com.siemens.pki.cmpracomponent.msgvalidation.ProtectionValidator.validate(ProtectionValidator.java:78)
	at com.siemens.pki.cmpclientcomponent.main.ClientRequestHandler$ValidatorAndProtector.validateResponse(ClientRequestHandler.java:129)
	at com.siemens.pki.cmpclientcomponent.main.ClientRequestHandler.sendReceiveValidateMessage(ClientRequestHandler.java:334)
	at com.siemens.pki.cmpclientcomponent.main.CmpClient.invokeEnrollment(CmpClient.java:482)
```

**Comment by Akretsch** [comment]
EjbCA bug.

**Comment by DDvO** [comment]
The EBJCA responded with a negative `ip` message containing the stattusString
```
Request public key can not be empty without providing a suitable protocolEncrKey (RSA)
```
So maybe it can support central key generation, while not in the way we expect it.
